apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "strapi.fullname" . }}-entrypoint
data:
  init-strapi.sh: |
    #!/bin/sh
    set -ea

    # Check if admin exists
    if [ -f "/opt/app/strapi/.env" ]; then
      echo "Existing Strapi installation found"
      # Restore existing configuration
      cp -r /opt/app/strapi/* /app/
      npm install
    else
      echo "New Strapi installation"
      # Create new project
      strapi new . --dbclient=postgres \
        --dbhost={{ .Values.postgresql.auth.host | default (printf "%s-postgresql" (include "strapi.fullname" .)) }} \
        --dbport={{ .Values.postgresql.auth.port | default "5432" }} \
        --dbname={{ .Values.postgresql.auth.database }} \
        --dbusername={{ .Values.postgresql.auth.username }} \
        --dbpassword={{ .Values.postgresql.auth.password }} \
        --dbssl=false

      # Save configuration
      mkdir -p /opt/app/strapi
      cp -r /app/* /opt/app/strapi/
    fi

    # Start Strapi
    npm run develop 