apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "strapi.fullname" . }}
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "strapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "strapi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 1337
          command: ["/bin/sh"]
          args: ["-c", "/scripts/init-strapi.sh"]
          volumeMounts:
            - name: init-script
              mountPath: /scripts
            - name: strapi-data
              mountPath: /opt/app
  volumes:
    - name: init-script
      configMap:
        name: {{ include "strapi.fullname" . }}-entrypoint
        defaultMode: 0755
    - name: strapi-data
      persistentVolumeClaim:
        claimName: {{ include "strapi.fullname" . }}-data