apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strapi.fullname" . }}
type: Opaque
data:
  ADMIN_JWT_SECRET: {{ .Values.adminJWTSecret | b64enc | quote }}
  {{ if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{ end }}
  {{ if .Values.postgresql.enabled }}
  DATABASE_URL: {{ include "strapi.internalDatabaseUrl" . | b64enc | quote }}
  POSTGRES_DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_DB_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  {{ end }}
  {{ if .Values.s3.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accesKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.accessSecret | b64enc | quote }}
  AWS_ENDPOINT: {{ .Values.s3.endpoint | b64enc | quote }}
  AWS_BUCKET: {{ .Values.s3.bucket | b64enc | quote }}
  {{ end }}
  {{ if .Values.r2.enabled }}
  CF_ACCESS_KEY_ID: {{ .Values.r2.accesKeyId | b64enc | quote }}
  CF_SECRET_ACCESS_KEY: {{ .Values.r2.accessSecret | b64enc | quote }}
  CF_ENDPOINT: {{ .Values.r2.endpoint | b64enc | quote }}
  CF_BUCKET: {{ .Values.r2.bucket | b64enc | quote }}
  {{ end }}